### ISSUE TITLE
Práctica 8.-Roadmap_Canban

### ISSUE THREAD

**Issue by yanet02** [SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-equipo-ycej#4]
[Práctica 8.-Edwin_Yanet_Carlos_Jeronima.pdf](https://github.com/user-attachments/files/17548095/Practica.8.-Edwin_Yanet_Carlos_Jeronima.pdf)

**Comment by Nelsy21** [comment]
Portada: 25 puntos
Describe el procedimiento: 25 puntos
Incluye ilustraciones y capturas: 25 puntos
Conclusión: 25 puntos
Puntaje alcanzado 100% = 20 puntos

**Comment by yanet02** [comment]
https://github.com/SistemasTecTlaxiaco/actividad-8-planificacion-roadmap-y-kanban-equipo-ycej/issues

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
